min-players: 2 #Minimum amount of players to start the round
max-players: 4
countdown: 5 # In seconds. Will be used once min-players is reached
players-per-team: 2 #Maximum amount of players in a team
lobby-spawn: ##Where new players spawn
  ==: org.bukkit.Location
  world: world
  x: 43.5
  y: 86.0
  z: 254.5
  pitch: 0.0
  yaw: -90.0
wait-time:
  - 5
  - 3
  - 2
  - 1
teams:
  yellow:
    color: e
    spawnpoints:
      - ==: org.bukkit.Location
        world: world
        x: 43.5
        y: 86.0
        z: 254.5
        pitch: 0.0
        yaw: -90.0
    beds:
      - ==: org.bukkit.Location
        world: world
        x: 40.0
        y: 86.0
        z: 254.0
        pitch: 0.0
        yaw: 0.0
  blue:
    color: 1
    spawnpoints:
      - ==: org.bukkit.Location
        world: world
        x: 57.5
        y: 86.0
        z: 256.5
        pitch: 0.0
        yaw: 90.0
    beds:
      - ==: org.bukkit.Location
        world: world
        x: 60.0
        y: 86.0
        z: 254.0
        pitch: 0.0
        yaw: 0.0