name: BW
version: ${project.version}
author: Keyinator
website: www.keyinator.net
main: net.keyinator.bw.Main
api-version: "1.15"
commands:
  bw:
    description: bw
    usage: /bw add [team|spawnpoint] [name|name] [color]
permissions:
  bw.breakInLobby:
    description: Allows to break blocks in the lobby
    default: op